# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Post.create([
  {title: "Post 1", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultrices enim felis, sed molestie elit tristique in. Aliquam accumsan erat sed leo porta, at fermentum nisl laoreet. Pellentesque dignissim tellus enim, in auctor nunc mollis sit amet. Vestibulum orci purus, volutpat vel finibus placerat, fringilla at diam. Nam eget viverra orci. Curabitur blandit venenatis blandit. Ut rhoncus, risus sit amet eleifend elementum, felis tortor gravida sapien, eget egestas enim arcu id orci. Nullam non condimentum eros. Duis ultrices sed justo ac congue. Fusce dapibus mauris vitae metus pretium, eget interdum eros ultrices. Integer vel viverra dui. Aenean non tortor quis mauris commodo condimentum vitae vel arcu. Duis pretium massa vel luctus gravida. Aenean consectetur felis ac condimentum sagittis. Nullam et pretium diam, et blandit metus. Nunc lobortis ultricies augue, eu tincidunt leo volutpat at. Mauris dignissim arcu urna, sit amet molestie ante condimentum in. Vestibulum in ex et dui scelerisque tristique. Suspendisse a ante ut augue congue scelerisque. Fusce sit amet finibus dui, in tincidunt libero. Donec non congue massa, nec imperdiet odio. Vestibulum varius mi at iaculis finibus. Curabitur non augue orci. Donec porta aliquam dictum. Mauris massa nisl, cursus a blandit tempus, consectetur at tellus. Mauris tincidunt odio at tellus varius ornare."},
  {title: "Post 2", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultrices enim felis, sed molestie elit tristique in. Aliquam accumsan erat sed leo porta, at fermentum nisl laoreet. Pellentesque dignissim tellus enim, in auctor nunc mollis sit amet. Vestibulum orci purus, volutpat vel finibus placerat, fringilla at diam. Nam eget viverra orci. Curabitur blandit venenatis blandit. Ut rhoncus, risus sit amet eleifend elementum, felis tortor gravida sapien, eget egestas enim arcu id orci. Nullam non condimentum eros. Duis ultrices sed justo ac congue. Fusce dapibus mauris vitae metus pretium, eget interdum eros ultrices. Integer vel viverra dui. Aenean non tortor quis mauris commodo condimentum vitae vel arcu. Duis pretium massa vel luctus gravida. Aenean consectetur felis ac condimentum sagittis. Nullam et pretium diam, et blandit metus. Nunc lobortis ultricies augue, eu tincidunt leo volutpat at. Mauris dignissim arcu urna, sit amet molestie ante condimentum in. Vestibulum in ex et dui scelerisque tristique. Suspendisse a ante ut augue congue scelerisque. Fusce sit amet finibus dui, in tincidunt libero. Donec non congue massa, nec imperdiet odio. Vestibulum varius mi at iaculis finibus. Curabitur non augue orci. Donec porta aliquam dictum. Mauris massa nisl, cursus a blandit tempus, consectetur at tellus. Mauris tincidunt odio at tellus varius ornare."},
  {title: "Post 3", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut ultrices enim felis, sed molestie elit tristique in. Aliquam accumsan erat sed leo porta, at fermentum nisl laoreet. Pellentesque dignissim tellus enim, in auctor nunc mollis sit amet. Vestibulum orci purus, volutpat vel finibus placerat, fringilla at diam. Nam eget viverra orci. Curabitur blandit venenatis blandit. Ut rhoncus, risus sit amet eleifend elementum, felis tortor gravida sapien, eget egestas enim arcu id orci. Nullam non condimentum eros. Duis ultrices sed justo ac congue. Fusce dapibus mauris vitae metus pretium, eget interdum eros ultrices. Integer vel viverra dui. Aenean non tortor quis mauris commodo condimentum vitae vel arcu. Duis pretium massa vel luctus gravida. Aenean consectetur felis ac condimentum sagittis. Nullam et pretium diam, et blandit metus. Nunc lobortis ultricies augue, eu tincidunt leo volutpat at. Mauris dignissim arcu urna, sit amet molestie ante condimentum in. Vestibulum in ex et dui scelerisque tristique. Suspendisse a ante ut augue congue scelerisque. Fusce sit amet finibus dui, in tincidunt libero. Donec non congue massa, nec imperdiet odio. Vestibulum varius mi at iaculis finibus. Curabitur non augue orci. Donec porta aliquam dictum. Mauris massa nisl, cursus a blandit tempus, consectetur at tellus. Mauris tincidunt odio at tellus varius ornare."}
])
